const data = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "470939",
      name: "Biryani By Kilo",
      uuid: "1d90cd81-5202-442e-ba90-2b28e6ca6314",
      city: "79",
      area: "Mithapur",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "szqn1oevvrtmlrvtrnog",
      cuisines: [
        "Biryani",
        "Hyderabadi",
        "North Indian",
        "Kebabs",
        "Mughlai",
        "Desserts",
      ],
      tags: [],
      costForTwo: 49900,
      costForTwoString: "₹499 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "biryani-by-kilo-ashok-nagar-kankarbagh",
        city: "patna",
      },
      cityState: "79",
      address:
        "First Floor, Nawab Heritage, Main Road, Ashok Nagar, Nauratanpur, Kankarbagh,Patna, Bihar-800020",
      locality: "Ashok Nagar",
      parentId: 130,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=7041187~p=1~eid=00000188-80a9-3b9a-0e2d-533a0015012c",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "470939",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "242395",
      name: "Ram Babu Restaurant",
      uuid: "d681e274-d851-4cd9-ba53-8cfe1810572d",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "mq1vlwbzjanzdeukja3d",
      cuisines: ["Chinese", "North Indian", "Biryani"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: "37 MINS",
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: "ram-babu-restaurant-kankarbagh-kankarbagh",
        city: "patna",
      },
      cityState: "79",
      address: "Chandmadi road,Kankarbagh,patna - 800020",
      locality: "Chandmadi road",
      parentId: 166239,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "242395",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "88781",
      name: "Sujata Family Restaurant",
      uuid: "3ac5f62e-fca8-4c33-8fdc-4603804bb14a",
      city: "79",
      area: "Fraser Road",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "np13tsnfrxylkrk1ykm5",
      cuisines: ["Mughlai", "Chinese", "North Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 2.700000047683716,
      slugs: {
        restaurant: "sujata-family-restaurant-fraser-road-fraser-road",
        city: "patna",
      },
      cityState: "79",
      address: "Hotel Mayur, Fraser Road Area, Patna",
      locality: "",
      parentId: 196672,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "88781",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 2.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "715341",
      name: "BODYPOWER CAFE",
      uuid: "20e7ff9f-5990-4257-8eeb-3bb38b6d0c86",
      city: "79",
      area: "Srikrishnapuri",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "259140b514b5dd3e75f012acc24e196f",
      cuisines: ["Healthy Food", "Salads", "Continental"],
      tags: [],
      costForTwo: 45000,
      costForTwoString: "₹450 FOR TWO",
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: "37 MINS",
      lastMileTravel: 3.9000000953674316,
      slugs: {
        restaurant: "bodypower-cafe-srikrishnapuri-srikrishnapuri",
        city: "patna",
      },
      cityState: "79",
      address:
        "Mahavir Ln, Sri Krishna Nagar, Buddha Colony, Patna, Bihar 800001, India",
      locality: "Sri Krishna Nagar",
      parentId: 280671,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6895677~p=4~eid=00000188-80a9-3b9a-0e2d-533b00150418",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "3.9 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "715341",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 3.9000000953674316,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "5.0",
      totalRatings: 20,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "132703",
      name: "Dosa Station",
      uuid: "88548026-0dfa-457d-a8c0-f6f4dea37b58",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "rv8vzoxlvdb80jwvx21h",
      cuisines: ["South Indian"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "dosa-station-kankarbagh-kankarbagh",
        city: "patna",
      },
      cityState: "79",
      address: "P.c Colony, East A Nagar, Kankarbagh, Patna",
      locality: "P C Colony",
      parentId: 19938,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "132703",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.0",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "152335",
      name: "Hungry Hope",
      uuid: "9ef51d0d-3f4a-49c8-8601-3c3b16f816e5",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "cv4hmfd42qioasn0tqtd",
      cuisines: ["Indian", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: "34 MINS",
      lastMileTravel: 2.5999999046325684,
      slugs: { restaurant: "hungry-hope-kankarbagh-kankarbagh", city: "patna" },
      cityState: "79",
      address: "Shila Ram Complex, Kankarbagh, Patna",
      locality: "RBI Flats Colony",
      parentId: 104720,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "152335",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "386042",
      name: "SHAKE BOX",
      uuid: "7f82aa2f-10d3-44cc-a514-e47ac43ada34",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "dipqte2akrewtqs4zjbf",
      cuisines: ["Beverages", "Ice Cream"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 2.200000047683716,
      slugs: { restaurant: "shake-box-kankarbagh-kankarbagh", city: "patna" },
      cityState: "79",
      address: "NEAR KFC KANKARBAGH, MAIN ROAD, PATNA SADAR, PATNA",
      locality: "PC Colony",
      parentId: 254814,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6863075~p=7~eid=00000188-80a9-3b9a-0e2d-533c0015076e",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "386042",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 2.200000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.8",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "659435",
      name: "Haldiram (Kadamkuan)",
      uuid: "ae5a3d44-7fb1-41b3-acc7-bfe10dbf95d1",
      city: "79",
      area: "Kadam Kuan",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "779fe291c901340e065dd6d64b742b9d",
      cuisines: [
        "Sweets",
        "Indian",
        "Snacks",
        "South Indian",
        "North Indian",
        "Thalis",
        "Chinese",
        "Fast Food",
        "Tandoor",
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: "37 MINS",
      lastMileTravel: 3.5,
      slugs: { restaurant: "haldiram-kankarbagh-kankarbagh", city: "patna" },
      cityState: "79",
      address:
        "Shop 007, Ground Floor, Ambition Ojha Plaza, Near Sahitya Sammelan Kadamkuan, Golambar, Patna",
      locality: "Rajendra Path",
      parentId: 396806,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "3.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "659435",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 3.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "591085",
      name: " 0612 Road Chef ( Kankarbagh)",
      uuid: "60f81790-ef98-41f5-b195-1a0c9fca266f",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "qo1ypqreeaulytd7cmgr",
      cuisines: ["Indian", "Tandoor", "Chinese", "Biryani"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 1.2999999523162842,
      slugs: {
        restaurant: "0612-road-chef-online-kankarbagh-kankarbagh",
        city: "patna",
      },
      cityState: "79",
      address: "SANJAY NAGAR ROAD NO.10 NEAR BY PASS ROAD KANKARBAGH",
      locality: "Sanjay Nagar Road",
      parentId: 353495,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "591085",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 1.2999999523162842,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "618450",
      name: "Matka Rasoi",
      uuid: "94a46b9e-6d42-4595-924e-a08f9906e1fa",
      city: "79",
      area: "G-31, P C Colony",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "102cf39edec49a7c96f2983da3d53999",
      cuisines: ["North Indian", "Biryani", "Kebabs"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: "34 MINS",
      lastMileTravel: 2.5,
      slugs: {
        restaurant: "matka-rasoi-srikrishnapuri-srikrishnapuri",
        city: "patna",
      },
      cityState: "79",
      address:
        "G-31, P C Colony, Kankarbagh, Patna Sadar, Patna, Bihar, 800020",
      locality: "New Patliputra Colony",
      parentId: 368677,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6854408~p=10~eid=00000188-80a9-3b9a-0e2d-533d00150a69",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "618450",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "87385",
      name: "Khana Khazana",
      uuid: "b31ad21f-cd4b-41b2-8bbd-8abcd5f085ca",
      city: "79",
      area: "Sri Krishnapuri",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "jxaulq6vdq1laxrtiufo",
      cuisines: ["North Indian", "Chinese", "Biryani"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 4.199999809265137,
      slugs: {
        restaurant: "khana-khazana-boring-road-srikrishnapuri",
        city: "patna",
      },
      cityState: "79",
      address:
        "Gorakhnath Compound, Behind Trishul Market, E Boring Canal Road, Sri Krishnapuri, Patna",
      locality: "Boring Road",
      parentId: 2928,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2600, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "4.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "87385",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 4.199999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.4",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "118491",
      name: "Cake Palace",
      uuid: "abfb5abd-5eab-40eb-8007-507e8d81e7fc",
      city: "79",
      area: "Golambar",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "pxaaijls6qfgpwzvyl72",
      cuisines: ["Desserts", "Bakery"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 3.700000047683716,
      slugs: { restaurant: "cake-palace-golamber-golambar", city: "patna" },
      cityState: "79",
      address:
        "janak kishore road, near sudha Booth, beside Hindi sahitya Sammelan, kadamkuan, patna",
      locality: "Janak Kishore Road",
      parentId: 11241,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "3.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹199",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "118491",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 3.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "611043",
      name: "La Pino'z Pizza",
      uuid: "2c672757-7f7c-4b20-8e91-1b2d77205e5e",
      city: "79",
      area: "Golambar",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "pwllxm2marsfiln5dlvi",
      cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 33,
      minDeliveryTime: 33,
      maxDeliveryTime: 33,
      slaString: "33 MINS",
      lastMileTravel: 3.5999999046325684,
      slugs: {
        restaurant: "la-pinoz-pizza-south-gandhi-maidan-fraser-road",
        city: "patna",
      },
      cityState: "79",
      address:
        "A-5,A-6 Twin Tower , Hathua, South Gandhi Maidan , Patna - 800001",
      locality: "Old Jakkanpur",
      parentId: 4961,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [{ type: "PROMOTED" }],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "cid=6894214~p=16~eid=00000188-80a9-3b9a-0e2d-533f0015106d",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "3.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "15% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "611043",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        lastMileTravel: 3.5999999046325684,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.4",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "98898",
      name: "Kathi Junction",
      uuid: "f5e85098-6dc2-40b5-86fd-25d37b4b757a",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "yydpodxkblyvy5ocf5oo",
      cuisines: ["Indian", "Chinese"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 1.600000023841858,
      slugs: { restaurant: "kathi-junction-kankar-kankarbagh", city: "patna" },
      cityState: "79",
      address:
        "J-4, P.C.Colony, Behind Shankar chikitsalay, Kankarbagh, Patna -800020",
      locality: "PC Colony",
      parentId: 1935,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "1.6 kms",
      hasSurge: false,
      sla: {
        restaurantId: "98898",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 1.600000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "246443",
      name: "HARILAL (Kankarbagh)",
      uuid: "ad5ff1d4-5533-4cec-9ca0-3ec0a298dbbb",
      city: "79",
      area: "Kankarbagh",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "cb3elcisgcyajxfsom43",
      cuisines: ["Bakery", "Sweets", "Indian"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 2.200000047683716,
      slugs: { restaurant: "harilal's-kankarbagh-kankarbagh", city: "patna" },
      cityState: "79",
      address: "gayatri mandir road, kankarbagh colony",
      locality: "Gayatri Mandir Road",
      parentId: 22072,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          { name: "distance", fee: 2100, message: "" },
          { name: "time", fee: 0, message: "" },
          { name: "special", fee: 0, message: "" },
        ],
        totalFees: 2100,
        message: "",
        title: "Delivery Charge",
        amount: "2100",
        icon: "",
      },
      availability: { opened: true, nextOpenMessage: "", nextCloseMessage: "" },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: { imageBased: [], textBased: [], textExtendedBadges: [] },
      lastMileTravelString: "2.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "246443",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 2.200000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
];

export default data;
